[build]
  command = "flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.16.0"
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

  [[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"
