[build]
  command = "flutter build web --release"
  publish = "build/web"
  environment = { PYTHON_VERSION = "3.13.2" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

  [[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"
